# Generated by Django 2.2.9 on 2020-05-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoToBeMeasured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_most_width', models.FloatField()),
                ('main_photo', models.ImageField(upload_to='images_to_measure/')),
            ],
        ),
    ]
